CREATE TABLE ACINFO (
PLACE VARCHAR2(20),
ID VARCHAR2(20) PRIMARY KEY,
PASS VARCHAR2(20),
AGE VARCHAR2(20),
PREFER VARCHAR2(50)
);

CREATE TABLE PLAYGROUND (
VICODE NUMBER PRIMARY KEY,
NAME VARCHAR2(10),
PRICE NUMBER,
THEMA VARCHAR2(20),
REVIEW VARCHAR2(200),
STAR NUMBER
);

CREATE SEQUENCE SEQ_P_CODE INCREMENT BY 1 START WITH 1;


